# Generated by Django 6.0.4 on 2026-05-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='patents_filed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='patents_granted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='patents_published',
        ),
        migrations.AddField(
            model_name='application',
            name='design_patents_filed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='design_patents_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='design_patents_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ug_pg_level',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='utility_patents_filed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='utility_patents_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='utility_patents_published',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('experience', 'Experience Certificate'), ('award', 'Award / Recognition'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='additional_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='recruitment.application')),
            ],
        ),
    ]
