# Generated by Django 6.0.4 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_application_patents_filed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='total_experience',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
