# Generated by Django 6.0.5 on 2026-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_application_total_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='suitability_statement',
            field=models.TextField(default='', help_text='Statement on how you are best suited for the post'),
        ),
        migrations.AddField(
            model_name='application',
            name='why_akgec',
            field=models.TextField(default='', help_text='Reason for choosing AKGEC'),
        ),
    ]
